define([], function() {
  return {
    "PropertyPaneDescription": "Configure Bing Maps Properties",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "CountMessageLong": "<b>{0}</b> results for '<em>{1}</em>'",
    "CountMessageShort": "<b>{0}</b> results",
    "hbsTemplateLabel" : "Info Pop-Up Template",
    "hbsTemplatePanelTitle" : "Info Pop-Up Handlebars Template",
    "inlineStylesTitle": "Info Pop-Up Styles",
    "inlineStylesPanelTitle": "Info Pop-Up CSS Styles",
    "compareTypeAltTagText" : "Contains Text (use comma for multiple values)",
    "compareTypeRegExText" : "Contains Text (use comma for multiple values)",
    "compareTypeLabel":"Comparison Type",
    "urlLabel" : "URL of Icon to display",
    "patternLabel": "Match Category Field Value", 
    "categoryIconsLabel":"Category Pin Icons",
    "categoryIconsPanelHeader":"Enter custom icon urls to appear on the map pins.",
    "categoryIconsPanelDesc": "In the match column enter the text or regular expression that should be compared to category field value. In the URL column, enter the URL to an icon that should be displayed when that match equals true. Use pattern .* to match against all category values including null.",
    "categoryIconsButtonLabel" : "Specify Pin Icons",
    "columnsNameColumnTitle" : "Name",
    "columnsLabel" : "Request Columns",
    "columnsPanelHeader" : "Enter columns you want to request from the search service.",
    "columnsButtonLabel" : "Enter Column Names",
    "categoryColumnNameLabel" : "Category Column Name",
    "longitudeColumnNameLabel": "Longitude Column Name",
    "latitudeColumnNameLabel": "Latitude Column Name",
    "supportedMapTypesLabel": "Supported Map Types",
    "mapTypeIdLabel": "Default Map Type",
    "zoomLabel" :"Zoom",
    "bingMapsAPIKeyLabel": "Bing Maps API Key",
    "requiredField": "This is a required field.",
    "strokeColorLabel": "Line Color",
    "fillColorLabel":"Fill Color",
    "strokeThicknessLabel":"Line Thickeness",
    "showLabelsLabel":"Show Labels",
    "targetColumnNameLabel":"Target Column Name",
    "polygonColumnNameLabel":"Polygon Column Name",
    "titleColumnNameLabel" : "Title Column Name",
    "centerLongitudeLabel":"Center Longitude",
    "centerLatitudeLabel":"Center Latitude",
    "bingMapsGroupNameLabel" :"Bing Maps Properties",
    "columnConfigurationGroupLabel":"Column Configuration",
    "colorsStylesGroupLabel":"Colors & Styles",
    "stylesTemplatesGroupLabel":"Styles & Templates",
    "iconMappingsGroupLabel":"Icon Mappings",
    
  }
});